/**
 * sanitizeClickPath — resolve a push-payload clickPath against the
 * SW's own origin and reject anything not same-origin.
 *
 * Extracted from service-worker.ts (cp81-D22b) so the validation
 * logic can be unit-tested without instantiating a real Worker /
 * ServiceWorkerGlobalScope.
 *
 * Threat model:
 *
 *   The push payload is generated by the operator's relay.  An
 *   operator who turns malicious — or whose relay is compromised —
 *   could craft a clickPath that, when resolved as a URL relative
 *   to the SW's origin, ends up cross-origin.  Examples:
 *
 *     - `'//evil.com/login'`  → resolves to `https://evil.com/login`
 *                                (protocol-relative URL)
 *     - `'https://evil.com'`  → resolves to `https://evil.com/`
 *     - `'javascript:alert(1)'` → URL constructor accepts and
 *                                  preserves the javascript: scheme
 *     - `'mailto:a@b'`         → opens mail client
 *
 *   `WindowClient.navigate()` enforces same-origin per spec, but
 *   `clients.openWindow()` does NOT uniformly across browsers
 *   (Chrome will open cross-origin tabs from a SW context).
 *   The fix here is at the SW level: validate before either is
 *   called.
 *
 * Behavior:
 *
 *   - Non-string input → returns '/' (safe default).
 *   - Input that fails URL parsing → returns '/'.
 *   - Input that resolves to a different origin → returns '/'.
 *   - Input that resolves to the same origin → returns the
 *     pathname + search + hash portion (so internal routing
 *     keeps working).
 *
 * Returns a relative path (always starts with '/'); callers
 * combine it with the SW's origin via `new URL(path, origin)`.
 */
export function sanitizeClickPath(input: unknown, origin: string): string {
	if (typeof input !== 'string') return '/';
	try {
		const resolved = new URL(input, origin);
		if (resolved.origin !== origin) return '/';
		// Reject opaque-origin schemes (data:, blob:, etc.) by
		// requiring an http(s) protocol after resolution.  An
		// origin match alone isn't sufficient because data: URLs
		// have origin 'null' which equals 'null' — but the input
		// origin is always http(s) for a service worker.
		if (resolved.protocol !== 'http:' && resolved.protocol !== 'https:') {
			return '/';
		}
		return resolved.pathname + resolved.search + resolved.hash;
	} catch {
		return '/';
	}
}
