/**
 * sanitizeClickPath — resolve a push-payload clickPath against the
 * SW's own origin and reject anything not same-origin.
 *
 * Extracted from service-worker.ts so the validation
 * logic can be unit-tested without instantiating a real Worker /
 * ServiceWorkerGlobalScope.
 *
 * Threat model:
 *
 *   The push payload is generated by the operator's relay.  An
 *   operator who turns malicious — or whose relay is compromised —
 *   could craft a clickPath that, when resolved as a URL relative
 *   to the SW's origin, ends up cross-origin.  Examples:
 *
 *     - `'//evil.com/login'`  → resolves to `https://evil.com/login`
 *                                (protocol-relative URL)
 *     - `'https://evil.com'`  → resolves to `https://evil.com/`
 *     - `'javascript:alert(1)'` → URL constructor accepts and
 *                                  preserves the javascript: scheme
 *     - `'mailto:a@b'`         → opens mail client
 *
 *   Neither `WindowClient.navigate()` nor `clients.openWindow()`
 *   stops a cross-origin URL: navigate() performs the navigation and
 *   only resolves its promise with null afterwards, and openWindow()
 *   opens any URL. So the SW must validate before either is called.
 *
 *     - `'/.//evil.com/x'`, `'https://<origin>//evil.com/x'` resolve
 *       same-origin, but their pathname `//evil.com/x` becomes
 *       protocol-relative when the caller resolves it again — so the
 *       returned path is re-checked the way the caller uses it.
 *
 * Behavior:
 *
 *   - Non-string input → returns '/' (safe default).
 *   - Input that fails URL parsing → returns '/'.
 *   - Input that resolves to a different origin → returns '/'.
 *   - Input that resolves to the same origin → returns the
 *     pathname + search + hash portion (so internal routing
 *     keeps working).
 *
 * Returns a relative path (always starts with '/'); callers
 * combine it with the SW's origin via `new URL(path, origin)`.
 */
export function sanitizeClickPath(input: unknown, origin: string): string {
	if (typeof input !== 'string') return '/';
	try {
		const resolved = new URL(input, origin);
		if (resolved.origin !== origin) return '/';
		// Reject opaque-origin schemes (data:, blob:, etc.) by
		// requiring an http(s) protocol after resolution.  An
		// origin match alone isn't sufficient because data: URLs
		// have origin 'null' which equals 'null' — but the input
		// origin is always http(s) for a service worker.
		if (resolved.protocol !== 'http:' && resolved.protocol !== 'https:') {
			return '/';
		}
		const path = resolved.pathname + resolved.search + resolved.hash;
		// v1.20.0 review (F-3): `/.//evil.com`, `/..//evil.com` and
		// `https://<origin>//evil.com` all resolve SAME-origin with a pathname
		// that starts with `//`. The caller re-resolves the returned path
		// (`new URL(path, origin)`), which reads that as protocol-relative and
		// lands on evil.com. Check the result the way the caller will use it.
		if (path.startsWith('//') || new URL(path, origin).origin !== origin) return '/';
		return path;
	} catch {
		return '/';
	}
}
