# roles/fail2ban_monitor/handlers/main.yml
---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart morphit-fail2ban-monitor-timer
  ansible.builtin.systemd:
    name: morphit-fail2ban-monitor.timer
    state: restarted
