# roles/matrix_bot/handlers/main.yml
---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart morphit-matrix-bot
  ansible.builtin.systemd:
    name: morphit-matrix-bot
    state: restarted
