import { defineConfig } from 'vitest/config';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';

const src = (p: string) => resolve(fileURLToPath(new URL('./src', import.meta.url)), p);
const WEB_LIB = fileURLToPath(new URL('../web/src/lib', import.meta.url));

export default defineConfig({
	test: {
		// Unit tests only. Integration tests live under test/integration/
		// and are exercised via `npm run test:integration`.
		include: ['test/**/*.test.ts'],
		exclude: ['test/integration/**', 'node_modules/**'],
		environment: 'node',
		globals: false,
		// Tests touch no external services; each runs in isolation.
		isolate: true,
		// cp79-D21: uniform 30s per-test timeout across all
		// workspaces (relay applied at cp78-D19 after a confirmed
		// flake on scrypt-heavy tests).  Indexer's tests are fast
		// today (total 615ms for 481 tests = ~1.3ms avg), but
		// preemptively defending against the same dynamic-class
		// timing-under-contention bug class is essentially free.
		// Real hangs still fail fast within wall-clock budget.
		testTimeout: 30_000
	},
	// apps/web/tsconfig.json extends .svelte-kit/tsconfig.json, which is
	// generated by `svelte-kit sync` and does not exist in CI.  When vite
	// transforms files from apps/web/src/ (via the $web alias), its esbuild
	// wrapper calls loadTsconfigJsonForFile, walks up to apps/web/tsconfig.json,
	// and fails trying to resolve the missing extends.  Supplying tsconfigRaw
	// bypasses per-file tsconfig discovery for all esbuild transforms in this
	// vitest instance — the inline config is used directly instead.
	esbuild: {
		tsconfigRaw: {
			compilerOptions: {
				target: 'ES2023',
				module: 'ESNext',
				moduleResolution: 'bundler',
				strict: true,
				isolatedModules: true,
				skipLibCheck: true
			}
		}
	},
	resolve: {
		alias: {
			$config: src('config/index.ts'),
			$db: src('db'),
			$blurt: src('blurt'),
			$indexer: src('indexer'),
			$api: src('api'),
			$log: src('log/index.ts'),
			// Part 106: parity tests import the web-side validator.
			// Aliasing through vite's resolver avoids cross-workspace
			// relative-path resolution differences between host OSes.
			$web: WEB_LIB
		}
	}
});
