# roles/systemd_monitor/handlers/main.yml
---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart morphit-systemd-monitor-timer
  ansible.builtin.systemd:
    name: morphit-systemd-monitor.timer
    state: restarted
