#!/usr/bin/env tsx
/**
 * scripts/theme-tokens-smoke.ts — per-instance colour theming: the DEFAULT
 * theme must stay exactly the Morphit look (docs/BRANDING.md, "Colours").
 *
 * The colour values live in several places that must agree, and a drift in any
 * of them silently re-colours every unthemed instance (or makes a theme miss a
 * surface):
 *   TT-1  apps/web/src/theme.css (the ONE file the compiled CSS reads colours
 *         from) defines exactly the THEME_TOKENS of
 *         packages/operator-config/src/theme.ts, each with its Morphit value.
 *   TT-2  deriveTheme(Morphit preset) reproduces those values exactly (so
 *         `branding apply --theme morphit` / no theme = canonical bytes).
 *   TT-3  tailwind.config.js maps its colours only to defined tokens.
 *   TT-4  The theme-color slot: src/app.html's meta, build-brand-slots.mjs's
 *         CANONICAL_THEME_COLOR and the token brand-2 agree.
 *   TT-5  static/manifest.webmanifest's theme/background colours are the
 *         brand-2 / surface-page tokens (branding rewrites them from a theme).
 *   TT-6  Icons generated by branding sit on the surface-page canvas by default.
 *   TT-7  The theme <style> id is the same in ops-cli's writer and the web's
 *         reader (applyTheme leaves a server-themed page alone by that id).
 *   TT-8  When a built frontend is present (apps/web/build), its COMPILED CSS
 *         :root carries exactly the Morphit token values.
 *
 * The full pixel-level proof (screenshots of a build before/after, plus a
 * compiled-rule equivalence check) is apps/web/scripts/theme-pixel-check.mjs —
 * too heavy for the battery (needs Chromium); see its header.
 */
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
	THEME_TOKENS,
	THEME_STYLE_ID,
	deriveTheme,
	hexToRgbTriplet
} from '../packages/operator-config/src/theme.ts';
import { CANONICAL_THEME_COLOR } from './build-brand-slots.mjs';
import { composeAppIconSvg, normalizeSvg } from '../apps/ops-cli/src/lib/branding.ts';
import { THEME_STYLE_ID as WEB_STYLE_ID } from '../apps/web/src/lib/brand/applyTheme.ts';

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const WEB = join(REPO, 'apps', 'web');

let failed = 0;
let passed = 0;
function check(name: string, ok: boolean, detail = ''): void {
	if (ok) {
		console.log(`  ✓ ${name}`);
		passed++;
	} else {
		console.error(`  ✗ ${name}${detail ? `\n      ${detail}` : ''}`);
		failed++;
	}
}

/** `--x-rgb: R G B` declarations of the FIRST `:root {…}` block in a CSS text. */
function rootRgbVars(css: string): Map<string, string> {
	const out = new Map<string, string>();
	const noComments = css.replace(/\/\*[\s\S]*?\*\//g, '');
	const m = /:root\s*\{([^}]*)\}/.exec(noComments);
	if (!m) return out;
	for (const d of m[1]!.matchAll(/(--[a-z0-9-]+-rgb)\s*:\s*([^;]+);?/g))
		out.set(d[1]!, d[2]!.trim());
	return out;
}

console.log('\n── theme tokens smoke (default theme = the Morphit look) ──\n');

const expected = new Map(THEME_TOKENS.map((t) => [`--${t.name}-rgb`, hexToRgbTriplet(t.ref)]));

// TT-1
const themeCss = readFileSync(join(WEB, 'src', 'theme.css'), 'utf8');
const defined = rootRgbVars(themeCss);
const wrong = [...expected]
	.filter(([k, v]) => defined.get(k) !== v)
	.map(([k, v]) => `${k}: ${defined.get(k) ?? 'missing'} (want ${v})`);
const extra = [...defined.keys()].filter((k) => !expected.has(k));
check(
	`TT-1: src/theme.css defines exactly the ${expected.size} theme tokens with their Morphit values`,
	wrong.length === 0 && extra.length === 0,
	[...wrong, ...extra.map((k) => `${k}: not a THEME_TOKENS token`)].join('; ')
);
check(
	'TT-1b: src/theme.css defines the grid opacity 0.035',
	/--grid-opacity:\s*0\.035\s*;/.test(themeCss)
);

// TT-2
const d = deriveTheme({ preset: 'morphit' });
const drift = d.ok
	? THEME_TOKENS.filter((t) => d.palette.tokens[t.name] !== t.ref).map(
			(t) => `${t.name}: ${d.palette.tokens[t.name]} ≠ ${t.ref}`
		)
	: ['problems' in d ? d.problems.join('; ') : 'deriveTheme(morphit) failed'];
check(
	'TT-2: deriveTheme(morphit) reproduces every Morphit value exactly',
	d.ok && drift.length === 0 && d.palette.isDefault,
	drift.join('; ')
);

// TT-3
const tw = readFileSync(join(WEB, 'tailwind.config.js'), 'utf8')
	.replace(/\/\*[\s\S]*?\*\//g, '')
	.replace(/(^|\s)\/\/[^\n]*/g, '$1');
const twTokens = [...tw.matchAll(/token\('([a-z0-9-]+)'\)/g)].map((m) => m[1]!);
const twVars = [...tw.matchAll(/var\((--[a-z0-9-]+)\)/g)].map((m) => m[1]!);
const known = new Set([...expected.keys(), '--morphit-gradient']);
const unknown = [...twTokens.map((t) => `--${t}-rgb`), ...twVars].filter((v) => !known.has(v));
check(
	'TT-3: tailwind.config.js colours all come from defined theme tokens',
	twTokens.length >= 19 &&
		unknown.length === 0 &&
		/const token = \(name\) => `rgb\(var\(--\$\{name\}-rgb\) \/ <alpha-value>\)`/.test(tw),
	`unknown: ${unknown.join(', ') || '—'}; token() uses: ${twTokens.length}`
);

// TT-4
const brand2 = THEME_TOKENS.find((t) => t.name === 'brand-2')!.ref;
const appHtml = readFileSync(join(WEB, 'src', 'app.html'), 'utf8');
const meta = /<meta name="theme-color" content="([^"]+)"/.exec(appHtml)?.[1];
check(
	'TT-4: app.html theme-color == CANONICAL_THEME_COLOR == token brand-2',
	meta === CANONICAL_THEME_COLOR && CANONICAL_THEME_COLOR.toLowerCase() === brand2,
	`app.html ${meta}, slot builder ${CANONICAL_THEME_COLOR}, brand-2 ${brand2}`
);

// TT-5
const manifest = JSON.parse(
	readFileSync(join(WEB, 'static', 'manifest.webmanifest'), 'utf8')
) as Record<string, string>;
const page = THEME_TOKENS.find((t) => t.name === 'surface-page')!.ref;
check(
	'TT-5: manifest theme_color / background_color == brand-2 / surface-page',
	manifest.theme_color?.toLowerCase() === brand2 &&
		manifest.background_color?.toLowerCase() === page,
	`${manifest.theme_color} / ${manifest.background_color}`
);

// TT-6
const icon = composeAppIconSvg(
	normalizeSvg(
		'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1 1"><rect width="1" height="1"/></svg>',
		'x'
	),
	64,
	0.5
);
check(
	'TT-6: generated app icons default to the surface-page canvas',
	icon.includes(`fill="${page}"`)
);

// TT-7
check(
	'TT-7: theme <style> id agrees (ops-cli writer / web reader)',
	THEME_STYLE_ID === WEB_STYLE_ID && WEB_STYLE_ID === 'morphit-theme'
);

// TT-8
const assets = join(
	process.env.MORPHIT_WEB_BUILD ?? join(WEB, 'build'),
	'_app',
	'immutable',
	'assets'
);
if (existsSync(assets)) {
	const css = readdirSync(assets)
		.filter((f) => f.endsWith('.css'))
		.map((f) => readFileSync(join(assets, f), 'utf8'))
		.join('\n');
	const compiled = new Map<string, string>();
	for (const m of css.matchAll(/:root\{([^}]*)\}/g)) {
		for (const dcl of m[1]!.matchAll(/(--[a-z0-9-]+-rgb):([^;}]+)/g))
			compiled.set(dcl[1]!, dcl[2]!.trim());
	}
	const bad = [...expected]
		.filter(([k, v]) => compiled.get(k) !== v)
		.map(([k, v]) => `${k}: ${compiled.get(k) ?? 'missing'} (want ${v})`);
	check(
		'TT-8: the built frontend’s compiled CSS :root carries the Morphit values',
		bad.length === 0,
		bad.slice(0, 8).join('; ')
	);
} else {
	console.log(
		'  · TT-8: no apps/web/build here — compiled-CSS check not applicable (TT-1…TT-3 cover the sources)'
	);
}

if (failed > 0) {
	console.error(`\n✗ ${failed} of ${passed + failed} theme-token checks failed`);
	process.exit(1);
}
console.log(`\n✓ all ${passed} theme-token checks passed`);
