-- Morphit indexer — migration v12.
--
-- Phase 5d cleanup — drop dead syndication columns from `orders`.
--
-- v11 added these columns for a syndication design that was later
-- revised before shipping. The current implementation uses a
-- different mechanism (see docs/SYNDICATION-CHECKPOINT.md + Post A/B
-- patterns in the frontend) that does not consult either column.
-- Neither column is read or written anywhere in the current code:
--
--   - `syndicate_opt_in`: was intended as a boolean flag set when
--     the user opted into order-level syndication. The opt-in is now
--     a client-side boolean stored in a localStorage flag and a
--     per-order comment post, not an order-row column.
--
--   - `syndicated_trx_id`: was intended to memoize the trx_id of an
--     announcement post to prevent double-broadcast. The current
--     design uses a deterministic account-keyed permlink so duplicate
--     broadcasts are chain-idempotent (they become edits, not new
--     posts), making the memoization unnecessary.
--
-- IF EXISTS is defensive. The migration tracker prevents double-
-- application, but this guard makes the migration safe to replay
-- manually against a partially-reverted database.
--
-- Reversibility: trivial. If someone ever wants these columns back,
-- they can be re-added by re-applying v11's DDL. The columns held
-- no data worth preserving (values were the defaults everywhere).

ALTER TABLE orders DROP COLUMN IF EXISTS syndicate_opt_in;
ALTER TABLE orders DROP COLUMN IF EXISTS syndicated_trx_id;
